import './globals.css'
// import "react-calendar/dist/Calendar.css";
import "@/components/calendar/MiniCalendar.css";
import RootStructure from './RootStructure';
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'HCMUT Assignment',
  description: 'Generated by create next app',
  applicationName: 'HCMUT',
  keywords: ["react", "server components", 'nextjs', 'tailwind', 'admin', 'dashboard'],
  themeColor: '#422AFB',
  icons: [
    { rel: "favicon", type: 'image/ico', url: "/favicon.ico" },
    { rel: "thumbnail", type: 'image/png', url: "/img/auth/auth.png" }
  ],
  generator: 'nhatdev',
  authors: [{ name: 'nhatdev' }],
  creator: 'nhatdev'
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <RootStructure childrenProps={children} />
  );
}